name: Build&Test

on: [push]

jobs:
  BuildAndTest:
    runs-on:
      windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x

      - name: Build with dotnet
        run: dotnet build 

      - name: Execute unit tests
        run: dotnet test -c Debug
